#!/bin/bash -x

deploy_javadoc() {
  project=${1}
  workspace=${2}
  sites=${3}

  source=${2}/${project}/target/site/apidocs/
  destination=${sites}/${project}

  rm -r -f ${destination}/apidocs
  mkdir -p ${destination}/apidocs
  cp -r ${source} ${destination}
  chown -R www-data:www-data ${destination}
}


#
# Generating documentation
#

# Define the place where all projects are developed
workspace=~/workspace

# Define the place where my Maven websites are deployed to Apache2
sites=/home/maven2/jquantlib.org/maven2/sites


if [ -z "$1" ] ;then
  project=jquantlib
else
  project="$1"
fi
  
if [ `whoami` == "root" ] ; then
  deploy_javadoc ${project} ${workspace} ${sites}
fi
