#!/bin/bash

generate_javadoc() {

  project=${1}
  packages=${2}
  workspace=${3}
  srcfolder=${4}

  source=${workspace}/${project}/${srcfolder}
  destination=${workspace}/${project}/target/site/apidocs/

  javadoc \
	-d ${destination} \
	-private \
	-taglet net.sf.latextaglet.LaTeXInlineTaglet \
	-taglet net.sf.latextaglet.LaTeXBlockEquationTaglet \
	-taglet net.sf.latextaglet.LaTeXEquationTaglet \
	-tagletpath /opt/JavaIDE/lib/latextaglet-0.1.0.jar \
	-doclet gr.spinellis.umlgraph.doclet.UmlGraphDoc \
	-docletpath /opt/JavaIDE/lib/UmlGraph-4.9.jar \
	-sourcepath ${source} \
	-subpackages ${packages}
}



# Define the place where all projects are developed
workspace=~/workspace


#
# Generating documentation
#

if [ -z "$1" ] ;then
  app=jquantlib
else
  app="$1"
fi
  
case "$app" in
  jquantlib   ) #gendocs_jquantlib;;
	project=jquantlib
	packages=org.jquantlib;;
  latextaglet ) #gendocs_latextaglet;;
	project=latextaglet
	packages=net.sf.latextaglet;;
  test )
	project=test
	packages=com.example;;
  * ) echo $0 : application not found : "$app"
      exit 1;;
esac

generate_javadoc ${project} ${packages} ${workspace} src/main/java
generate_javadoc ${project} ${packages} ${workspace} src/test/java
