#!/bin/bash

# echo tagtex ${1} ${2}

cd ${1}

latex ${2}.tex
dvipng -T tight -x 1200 -z 9 -bg transparent ${2}.dvi
mv ${2}1.png ${2}.png

#ls -al ${2}.png

rm ${2}.tex
rm ${2}.dvi
rm ${2}.log
rm ${2}.aux
